### ISSUE TITLE
No information on Barcharts?

### ISSUE THREAD

**Issue by AnilGupte** [Noterik/NoterikDataVisualizations#2]
What are the available settings for BarCharts?  I tried using it, and it sort of works, but there are issues:
1. It does not use the colors assigned to the data.
2. Font-color does not change
3. A % sign is being added to the left (y) axis (displayPercent: false, does not help)
4. It appears to be using an arbitrary scale on the y axis and I have no idea how that is defined.

I am using the following code:
var barchart = $('#A1Card').ntkBarChart({
    data: data,
    fontFamily: "Verdana,sans-serif",
    fontColor: "#FF0000",
	displayPercent: false,
    margin: {
      top: 20,
      right: 20,
      bottom: 30,
      left: 60
    }
});
and including:
<script src="../js/d3.min.js"></script>
<script src="../js/noterik-data-visualizations-1.1.2.min.js"></script>

**Comment by DavidAmmeraal** [comment]
Hi Anil,

The BarChart was never completed, so I have removed it from the master branch and moved it to a feature branch (https://github.com/Noterik/NoterikDataVisualizations/tree/feature/bar-chart). 

Please note that we have not concrete planning on when this will be completed. And if we might require a bar chart for one of our projects, we might not put it into this repo as we're not actively using jQuery anymore in most of our projects. 

You're always welcome to finish it yourself.
