### ISSUE TITLE
Control over text in PieCharts requested

### ISSUE THREAD

**Issue by AnilGupte** [Noterik/NoterikDataVisualizations#3]
First, let me congratulate you and thank you for an excellent tool.  I tried several others and yours is no doubt the best - most flexible and works great.

May I request some control over the text in the PieCharts?  As you can see from the attached image, text does overlap.
![piechartnoterikoverlap](https://user-images.githubusercontent.com/9494017/33303982-2e2d5498-d42c-11e7-99a2-6c5300c9997e.JPG)

Also, it would be nice if the PieChart fit into the Div and took into account the padding of the Div.

Thanx again!

**Comment by AnilGupte** [comment]
Giving the text a class and each text item a unique id will do the trick.  I can then post-process the text by looping through all items in the class, checking against overlaps by id and changing the transform values if they are.

**Comment by DavidAmmeraal** [comment]
Hi Anil,

Apologies for the delayed response. This repo is quite old, but nice to see someone still using it. I've looked into your request and implemented a labelCallback with which labels can be customized. I've put this into pull request #6 which is on the 1.3.0 branch.

Please check https://github.com/Noterik/NoterikDataVisualizations/blob/1.3.0/README.md#customization for more information.

**Comment by AnilGupte** [comment]
Excellent! This works!  It would have been nice to have a class attached too, but I can do that with an ID wildcard.

**Comment by DavidAmmeraal** [comment]
You should be able to attach a class like this:

```javascript
var piechart = $('#piechart').ntkPieChart({
  data: data,
  labelCallback: function(element){ // Element is a D3 selected element that is being rendered for the current data entry.
    return element.attr("class", function(entry){ // Entry contains a reference to the current data entry being rendered.
      return "label";
    })
  }
});

**Comment by AnilGupte** [comment]
The ID wildcard thing is not working  Is there something special about text or this text label created by a callback that will not respond to a select by ID?  Weird things are happening - I can see the ID that has been created (see screenshot) but when I right click and copy the Outer HTML in the FireFox Inspector, the ID doesn't show:
![noterik1](https://user-images.githubusercontent.com/9494017/33866917-5220c468-df1f-11e7-846e-8f7c35c9169e.JPG)







`<text transform="translate(-49.20799652923715,-63.07593104805179)" style="font-family: Verdana, sans-serif; fill: rgb(255, 255, 255);" id="label_DOPPackages2">Day 2 13 (0%)</text>
`
And the jQuery slectors give me nothing. I tried first

var DOP = $("[id^=label]");

I got an object but everything inside is undefined and .lengthshows 0
I also tried directly

var test = $("#label_DOPPackagesGT2")

with the same result.  So, just to test, I tried

var test = $("#label_DOPPackagesGT2").css('color', 'red');

and it had not effect, meaning that it does not find the element.

**Comment by DavidAmmeraal** [comment]
Hi Anil,

I'm not really sure what's going wrong for you. However the following things are not correct:

```javascript
.css('color', 'red');
```

will not work, since changing the color of a text in a SVG requires 'fill' instead of 'color'. 

I'd also suggest just using the '#' selector for ID's, and also try searching on the piechart jQuery object itself.

This example works for me:

```javascript
var piechart = $('#piechart').ntkPieChart({
        data: data,
        labelCallback: function(element){
          return element
            .attr("id", function(entry, i){
              return "label_" + i;
         })
         .style("fill", function(){
           return "red";
         });
   } 
});

   const label = piechart.find('#label_0');
   label.css("fill", "blue");
```

**Comment by AnilGupte** [comment]
Thanx very much for your help.  I have finally got it to give me the coordinates.  Once last thing I am stuck at.  I am trying to get the Y coordinates of each item of text so that I can move them in the event of any overlap.  I use the following code:
```
function PostProcess() {
	var DOPList= $("[id^=label_DOP]")
	var str = "";
	for (n = 0 ; n < DOPList.length; n++){
		var el = DOPList[n];
		var bbox = el.getBBox();
		str += n + " " + bbox.y + " " + el.textContent + "\n";
	}
	alert(str);
}
```
I find that the value of bbox.y is the same for all items in DOPList but some of the text items are quite far apart.  Am I doing something wrong?  I want to test for each item to see if they overlap by comparing the Y-coordinate. For example, something like this: 

```
if (Math.abs(item[0].y - item[1].y) < item[0].(somefn to get font-height) ) {
      item[1].setAttributeNS(null, "y", -50);
}

```
Thanx again, and apologies for taking so much of your time.

**Comment by DavidAmmeraal** [comment]
Hi Anil,

I think your problem mainly has to do with the animation not having completed when you call your PostProcess function. I don't have time to introduce collision detection to this old library. But I've added callbacks and configuration options for the animations of the piechart, you can find them in the following branch:

https://github.com/Noterik/NoterikDataVisualizations/tree/feature/piechart-animations-settings-events

Please check https://github.com/Noterik/NoterikDataVisualizations/blob/feature/piechart-animations-settings-events/README.md#piechart-events for more information on how to use these.

I'd suggest listening for the "animation-finished" event and after that calling your PostProcess function. Please note that I don't have further time to investigate this issue, as it's not really something that's relevant for us at the moment. You're of course always free to look into forking this or doing a pull request for proper collision detection yourself (I'd suggest looking into the D3 QuadTree).

Regards

**Comment by AnilGupte** [comment]
Thanx  David for your help so far and I appreciate that you helped a lot despite this project not being of current interest to you.  I will follow up n your suggestions and see what I can do.  I am not that good at JavaScript nor am I too familiar with github to be able to do much, but I'll give it a shot. :-)

Thanx again!

**Comment by AnilGupte** [comment]
This is just FYI.  I still get the same values for bbox.yafter incorporating my PostProcess function in the piechart.on('slice-animation-finished', function.  I also tried piechart.on('text-animation-finished' and piechart.on('animation-finished' but get the same result.

I have meanwhile used a non-generalizable workaround (by using a semi-random translation in the y), that will suffice for now.

No expectations, I know this is not in your priorities.  Just FYI.  All the best!
